/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorldbuildingCategoryView = IDL.Record({
  'description' : IDL.Text,
  'freeformNotes' : IDL.Vec(IDL.Text),
});
export const CharacterView = IDL.Record({
  'flaws' : IDL.Text,
  'background' : IDL.Text,
  'storyRole' : IDL.Text,
  'voice' : IDL.Text,
  'name' : IDL.Text,
  'motivations' : IDL.Text,
  'relationships' : IDL.Text,
});
export const PrologueView = IDL.Record({
  'stakes' : IDL.Text,
  'povVoice' : IDL.Text,
  'hook' : IDL.Text,
  'keyReveals' : IDL.Text,
  'draft' : IDL.Text,
  'connectionToChapterOne' : IDL.Text,
});
export const BookProjectView = IDL.Record({
  'id' : IDL.Text,
  'worldbuilding' : IDL.Vec(WorldbuildingCategoryView),
  'name' : IDL.Text,
  'characters' : IDL.Vec(CharacterView),
  'prologue' : IDL.Opt(PrologueView),
});
export const BookSetupWorldbuildingCategoryAnswers = IDL.Record({
  'categoryName' : IDL.Text,
  'description' : IDL.Text,
  'freeformNotes' : IDL.Vec(IDL.Text),
});
export const BookSetupCharacterAnswers = IDL.Record({
  'flaws' : IDL.Text,
  'background' : IDL.Text,
  'voice' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'motivations' : IDL.Text,
  'relationships' : IDL.Text,
});
export const BookSetupAnswers = IDL.Record({
  'worldbuilding' : IDL.Vec(BookSetupWorldbuildingCategoryAnswers),
  'hasPrologue' : IDL.Bool,
  'characters' : IDL.Vec(BookSetupCharacterAnswers),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCharacter' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addWorldbuildingNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(BookProjectView)], ['query']),
  'getBookSetupAnswers' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BookSetupAnswers)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [BookProjectView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'renameProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveBookSetupAnswers' : IDL.Func([IDL.Text, BookSetupAnswers], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePrologue' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCharacter' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateWorldbuildingCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorldbuildingCategoryView = IDL.Record({
    'description' : IDL.Text,
    'freeformNotes' : IDL.Vec(IDL.Text),
  });
  const CharacterView = IDL.Record({
    'flaws' : IDL.Text,
    'background' : IDL.Text,
    'storyRole' : IDL.Text,
    'voice' : IDL.Text,
    'name' : IDL.Text,
    'motivations' : IDL.Text,
    'relationships' : IDL.Text,
  });
  const PrologueView = IDL.Record({
    'stakes' : IDL.Text,
    'povVoice' : IDL.Text,
    'hook' : IDL.Text,
    'keyReveals' : IDL.Text,
    'draft' : IDL.Text,
    'connectionToChapterOne' : IDL.Text,
  });
  const BookProjectView = IDL.Record({
    'id' : IDL.Text,
    'worldbuilding' : IDL.Vec(WorldbuildingCategoryView),
    'name' : IDL.Text,
    'characters' : IDL.Vec(CharacterView),
    'prologue' : IDL.Opt(PrologueView),
  });
  const BookSetupWorldbuildingCategoryAnswers = IDL.Record({
    'categoryName' : IDL.Text,
    'description' : IDL.Text,
    'freeformNotes' : IDL.Vec(IDL.Text),
  });
  const BookSetupCharacterAnswers = IDL.Record({
    'flaws' : IDL.Text,
    'background' : IDL.Text,
    'voice' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'motivations' : IDL.Text,
    'relationships' : IDL.Text,
  });
  const BookSetupAnswers = IDL.Record({
    'worldbuilding' : IDL.Vec(BookSetupWorldbuildingCategoryAnswers),
    'hasPrologue' : IDL.Bool,
    'characters' : IDL.Vec(BookSetupCharacterAnswers),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCharacter' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addWorldbuildingNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(BookProjectView)], ['query']),
    'getBookSetupAnswers' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BookSetupAnswers)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [BookProjectView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'renameProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveBookSetupAnswers' : IDL.Func([IDL.Text, BookSetupAnswers], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePrologue' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCharacter' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateWorldbuildingCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };