/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookProjectView {
  'id' : string,
  'worldbuilding' : Array<WorldbuildingCategoryView>,
  'name' : string,
  'characters' : Array<CharacterView>,
  'prologue' : [] | [PrologueView],
}
export interface CharacterView {
  'flaws' : string,
  'background' : string,
  'storyRole' : string,
  'voice' : string,
  'name' : string,
  'motivations' : string,
  'relationships' : string,
}
export interface PrologueView {
  'stakes' : string,
  'povVoice' : string,
  'hook' : string,
  'keyReveals' : string,
  'draft' : string,
  'connectionToChapterOne' : string,
}
export interface WorldbuildingCategoryView {
  'description' : string,
  'freeformNotes' : Array<string>,
}
export interface _SERVICE {
  'addCharacter' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'addWorldbuildingNote' : ActorMethod<[string, string, string], undefined>,
  'createProject' : ActorMethod<[string, string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<BookProjectView>>,
  'getProject' : ActorMethod<[string], BookProjectView>,
  'renameProject' : ActorMethod<[string, string], undefined>,
  'savePrologue' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateWorldbuildingCategory' : ActorMethod<
    [string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];