/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookProjectView {
  'id' : string,
  'worldbuilding' : Array<WorldbuildingCategoryView>,
  'name' : string,
  'characters' : Array<CharacterView>,
  'prologue' : [] | [PrologueView],
}
export interface BookSetupAnswers {
  'worldbuilding' : Array<BookSetupWorldbuildingCategoryAnswers>,
  'hasPrologue' : boolean,
  'characters' : Array<BookSetupCharacterAnswers>,
}
export interface BookSetupCharacterAnswers {
  'flaws' : string,
  'background' : string,
  'voice' : string,
  'name' : string,
  'role' : string,
  'motivations' : string,
  'relationships' : string,
}
export interface BookSetupWorldbuildingCategoryAnswers {
  'categoryName' : string,
  'description' : string,
  'freeformNotes' : Array<string>,
}
export interface CharacterView {
  'flaws' : string,
  'background' : string,
  'storyRole' : string,
  'voice' : string,
  'name' : string,
  'motivations' : string,
  'relationships' : string,
}
export interface PrologueView {
  'stakes' : string,
  'povVoice' : string,
  'hook' : string,
  'keyReveals' : string,
  'draft' : string,
  'connectionToChapterOne' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorldbuildingCategoryView {
  'description' : string,
  'freeformNotes' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCharacter' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'addWorldbuildingNote' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<BookProjectView>>,
  'getBookSetupAnswers' : ActorMethod<[string], [] | [BookSetupAnswers]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], BookProjectView>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'renameProject' : ActorMethod<[string, string], undefined>,
  'saveBookSetupAnswers' : ActorMethod<[string, BookSetupAnswers], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePrologue' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateCharacter' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'updateWorldbuildingCategory' : ActorMethod<
    [string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];