// Family Questionnaire question bank with stable IDs and typed definitions

export type QuestionType = 'radio' | 'select' | 'checkbox';

export interface QuestionOption {
  value: string;
  label: string;
  allowCustomInput?: boolean; // If true, show a short text input when this option is selected
}

export interface Question {
  id: string;
  section: string;
  type: QuestionType;
  question: string;
  options: QuestionOption[];
  description?: string;
}

export const FAMILY_QUESTIONNAIRE_SECTIONS = [
  'Background & Identity',
  'Personality & Traits',
  'Relationships & Social',
  'Goals & Motivations',
  'Conflicts & Challenges',
  'Voice & Expression',
  'Story Role & Arc',
] as const;

export const FAMILY_QUESTIONNAIRE_QUESTIONS: Question[] = [
  // Background & Identity (8 questions)
  {
    id: 'age-range',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their age range?',
    options: [
      { value: 'child', label: 'Child (0-12)' },
      { value: 'teen', label: 'Teenager (13-19)' },
      { value: 'young-adult', label: 'Young Adult (20-35)' },
      { value: 'middle-aged', label: 'Middle-Aged (36-55)' },
      { value: 'senior', label: 'Senior (56+)' },
    ],
  },
  {
    id: 'occupation',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their primary occupation or role?',
    options: [
      { value: 'student', label: 'Student' },
      { value: 'professional', label: 'Professional/Office Worker' },
      { value: 'creative', label: 'Creative/Artist' },
      { value: 'service', label: 'Service Industry' },
      { value: 'manual', label: 'Manual Labor/Trade' },
      { value: 'caregiver', label: 'Caregiver/Homemaker' },
      { value: 'retired', label: 'Retired' },
      { value: 'unemployed', label: 'Unemployed' },
      { value: 'other', label: 'Other', allowCustomInput: true },
    ],
  },
  {
    id: 'education',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their education level?',
    options: [
      { value: 'elementary', label: 'Elementary/Primary' },
      { value: 'high-school', label: 'High School' },
      { value: 'some-college', label: 'Some College' },
      { value: 'bachelors', label: "Bachelor's Degree" },
      { value: 'graduate', label: 'Graduate Degree' },
      { value: 'self-taught', label: 'Self-Taught/Informal' },
      { value: 'none', label: 'Limited Formal Education' },
    ],
  },
  {
    id: 'socioeconomic',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their socioeconomic background?',
    options: [
      { value: 'wealthy', label: 'Wealthy/Upper Class' },
      { value: 'comfortable', label: 'Comfortable/Upper Middle' },
      { value: 'middle', label: 'Middle Class' },
      { value: 'working', label: 'Working Class' },
      { value: 'struggling', label: 'Struggling/Lower Income' },
    ],
  },
  {
    id: 'upbringing',
    section: 'Background & Identity',
    type: 'radio',
    question: 'How would you describe their upbringing?',
    options: [
      { value: 'stable-loving', label: 'Stable and Loving' },
      { value: 'strict', label: 'Strict/Disciplined' },
      { value: 'chaotic', label: 'Chaotic/Unstable' },
      { value: 'neglectful', label: 'Neglectful' },
      { value: 'traumatic', label: 'Traumatic/Abusive' },
      { value: 'sheltered', label: 'Sheltered/Overprotected' },
      { value: 'independent', label: 'Independent/Self-Reliant Early' },
    ],
  },
  {
    id: 'cultural-background',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their cultural or ethnic background?',
    options: [
      { value: 'traditional', label: 'Traditional/Conservative Culture' },
      { value: 'modern', label: 'Modern/Progressive Culture' },
      { value: 'mixed', label: 'Mixed/Multicultural' },
      { value: 'immigrant', label: 'Immigrant/First Generation' },
      { value: 'indigenous', label: 'Indigenous/Native' },
      { value: 'other', label: 'Other', allowCustomInput: true },
    ],
  },
  {
    id: 'physical-appearance',
    section: 'Background & Identity',
    type: 'checkbox',
    question: 'Select notable physical characteristics (choose all that apply):',
    options: [
      { value: 'tall', label: 'Tall' },
      { value: 'short', label: 'Short' },
      { value: 'athletic', label: 'Athletic Build' },
      { value: 'distinctive-feature', label: 'Distinctive Feature (scar, tattoo, etc.)' },
      { value: 'stylish', label: 'Stylish/Fashion-Forward' },
      { value: 'casual', label: 'Casual/Practical Dresser' },
      { value: 'intimidating', label: 'Intimidating Presence' },
      { value: 'approachable', label: 'Approachable Appearance' },
    ],
  },
  {
    id: 'health-status',
    section: 'Background & Identity',
    type: 'radio',
    question: 'What is their general health status?',
    options: [
      { value: 'excellent', label: 'Excellent Health' },
      { value: 'good', label: 'Good Health' },
      { value: 'chronic-condition', label: 'Chronic Condition' },
      { value: 'disability', label: 'Physical Disability' },
      { value: 'mental-health', label: 'Mental Health Challenges' },
      { value: 'recovering', label: 'Recovering from Illness/Injury' },
    ],
  },

  // Personality & Traits (9 questions)
  {
    id: 'temperament',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'What is their general temperament?',
    options: [
      { value: 'calm', label: 'Calm and Even-Tempered' },
      { value: 'energetic', label: 'Energetic and Enthusiastic' },
      { value: 'serious', label: 'Serious and Reserved' },
      { value: 'volatile', label: 'Volatile/Quick-Tempered' },
      { value: 'melancholic', label: 'Melancholic/Moody' },
      { value: 'cheerful', label: 'Cheerful and Optimistic' },
    ],
  },
  {
    id: 'social-style',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'How do they interact socially?',
    options: [
      { value: 'extroverted', label: 'Extroverted/Outgoing' },
      { value: 'introverted', label: 'Introverted/Reserved' },
      { value: 'ambivert', label: 'Ambivert/Situational' },
      { value: 'socially-anxious', label: 'Socially Anxious' },
      { value: 'charismatic', label: 'Charismatic/Natural Leader' },
      { value: 'awkward', label: 'Socially Awkward' },
    ],
  },
  {
    id: 'decision-making',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'How do they make decisions?',
    options: [
      { value: 'logical', label: 'Logical and Analytical' },
      { value: 'emotional', label: 'Emotional and Intuitive' },
      { value: 'impulsive', label: 'Impulsive/Spontaneous' },
      { value: 'cautious', label: 'Cautious/Overthinking' },
      { value: 'collaborative', label: 'Collaborative/Seeks Input' },
      { value: 'decisive', label: 'Decisive/Confident' },
    ],
  },
  {
    id: 'moral-compass',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'What guides their moral compass?',
    options: [
      { value: 'principled', label: 'Strong Principles/Ethics' },
      { value: 'pragmatic', label: 'Pragmatic/Situational' },
      { value: 'self-interest', label: 'Self-Interest First' },
      { value: 'empathy', label: 'Empathy and Compassion' },
      { value: 'tradition', label: 'Tradition and Authority' },
      { value: 'rebellious', label: 'Rebellious/Questions Rules' },
    ],
  },
  {
    id: 'stress-response',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'How do they respond to stress?',
    options: [
      { value: 'calm-focused', label: 'Stay Calm and Focused' },
      { value: 'anxious', label: 'Become Anxious/Worried' },
      { value: 'angry', label: 'Become Angry/Aggressive' },
      { value: 'withdraw', label: 'Withdraw/Shut Down' },
      { value: 'seek-support', label: 'Seek Support from Others' },
      { value: 'denial', label: 'Denial/Avoidance' },
    ],
  },
  {
    id: 'humor-style',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'What is their sense of humor?',
    options: [
      { value: 'witty', label: 'Witty and Clever' },
      { value: 'sarcastic', label: 'Sarcastic/Dry' },
      { value: 'silly', label: 'Silly and Playful' },
      { value: 'dark', label: 'Dark Humor' },
      { value: 'wholesome', label: 'Wholesome/Gentle' },
      { value: 'serious', label: 'Serious/Rarely Jokes' },
    ],
  },
  {
    id: 'work-ethic',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'What is their work ethic?',
    options: [
      { value: 'workaholic', label: 'Workaholic/Driven' },
      { value: 'balanced', label: 'Balanced/Moderate' },
      { value: 'lazy', label: 'Lazy/Unmotivated' },
      { value: 'perfectionist', label: 'Perfectionist' },
      { value: 'procrastinator', label: 'Procrastinator' },
      { value: 'efficient', label: 'Efficient/Practical' },
    ],
  },
  {
    id: 'risk-tolerance',
    section: 'Personality & Traits',
    type: 'radio',
    question: 'How do they approach risk?',
    options: [
      { value: 'risk-taker', label: 'Risk-Taker/Adventurous' },
      { value: 'calculated', label: 'Calculated Risk-Taker' },
      { value: 'risk-averse', label: 'Risk-Averse/Cautious' },
      { value: 'reckless', label: 'Reckless/Impulsive' },
      { value: 'fearful', label: 'Fearful/Avoidant' },
    ],
  },
  {
    id: 'strengths',
    section: 'Personality & Traits',
    type: 'checkbox',
    question: 'Select their key strengths (choose up to 3):',
    options: [
      { value: 'intelligent', label: 'Intelligent/Quick Learner' },
      { value: 'compassionate', label: 'Compassionate/Kind' },
      { value: 'brave', label: 'Brave/Courageous' },
      { value: 'loyal', label: 'Loyal/Dependable' },
      { value: 'creative', label: 'Creative/Innovative' },
      { value: 'disciplined', label: 'Disciplined/Self-Controlled' },
      { value: 'charismatic', label: 'Charismatic/Persuasive' },
      { value: 'resilient', label: 'Resilient/Tough' },
    ],
  },

  // Relationships & Social (8 questions)
  {
    id: 'relationship-status',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'What is their romantic relationship status?',
    options: [
      { value: 'single', label: 'Single' },
      { value: 'dating', label: 'Dating/In a Relationship' },
      { value: 'married', label: 'Married/Partnered' },
      { value: 'divorced', label: 'Divorced/Separated' },
      { value: 'widowed', label: 'Widowed' },
      { value: 'complicated', label: "It's Complicated" },
      { value: 'not-interested', label: 'Not Interested in Romance' },
    ],
  },
  {
    id: 'family-dynamic',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'How would you describe their family dynamic?',
    options: [
      { value: 'close-supportive', label: 'Close and Supportive' },
      { value: 'distant', label: 'Distant/Estranged' },
      { value: 'complicated', label: 'Complicated/Mixed' },
      { value: 'toxic', label: 'Toxic/Dysfunctional' },
      { value: 'no-family', label: 'No Family/Orphaned' },
      { value: 'chosen-family', label: 'Chosen Family (non-biological)' },
    ],
  },
  {
    id: 'friendship-circle',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'What is their friendship circle like?',
    options: [
      { value: 'many-friends', label: 'Many Friends/Popular' },
      { value: 'few-close', label: 'Few Close Friends' },
      { value: 'one-best-friend', label: 'One Best Friend' },
      { value: 'loner', label: 'Loner/No Close Friends' },
      { value: 'acquaintances', label: 'Many Acquaintances, Few Deep Bonds' },
      { value: 'social-group', label: 'Part of a Tight-Knit Group' },
    ],
  },
  {
    id: 'trust-issues',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'How do they approach trust?',
    options: [
      { value: 'trusting', label: 'Trusting/Open' },
      { value: 'cautious', label: 'Cautious but Fair' },
      { value: 'suspicious', label: 'Suspicious/Guarded' },
      { value: 'naive', label: 'Naive/Too Trusting' },
      { value: 'betrayed', label: 'Betrayed in Past/Trust Issues' },
    ],
  },
  {
    id: 'conflict-style',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'How do they handle interpersonal conflict?',
    options: [
      { value: 'confrontational', label: 'Confrontational/Direct' },
      { value: 'avoidant', label: 'Avoidant/Passive' },
      { value: 'mediator', label: 'Mediator/Peacemaker' },
      { value: 'aggressive', label: 'Aggressive/Dominating' },
      { value: 'passive-aggressive', label: 'Passive-Aggressive' },
      { value: 'diplomatic', label: 'Diplomatic/Compromising' },
    ],
  },
  {
    id: 'communication-style',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'How do they communicate with others?',
    options: [
      { value: 'direct', label: 'Direct and Honest' },
      { value: 'diplomatic', label: 'Diplomatic/Tactful' },
      { value: 'blunt', label: 'Blunt/Insensitive' },
      { value: 'reserved', label: 'Reserved/Quiet' },
      { value: 'expressive', label: 'Expressive/Emotional' },
      { value: 'manipulative', label: 'Manipulative/Deceptive' },
    ],
  },
  {
    id: 'social-role',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'What role do they typically play in social groups?',
    options: [
      { value: 'leader', label: 'Leader/Organizer' },
      { value: 'follower', label: 'Follower/Supporter' },
      { value: 'mediator', label: 'Mediator/Peacekeeper' },
      { value: 'joker', label: 'Joker/Entertainer' },
      { value: 'outsider', label: 'Outsider/Observer' },
      { value: 'caregiver', label: 'Caregiver/Nurturer' },
    ],
  },
  {
    id: 'attachment-style',
    section: 'Relationships & Social',
    type: 'radio',
    question: 'What is their attachment style in close relationships?',
    options: [
      { value: 'secure', label: 'Secure/Balanced' },
      { value: 'anxious', label: 'Anxious/Clingy' },
      { value: 'avoidant', label: 'Avoidant/Distant' },
      { value: 'fearful', label: 'Fearful/Push-Pull' },
    ],
  },

  // Goals & Motivations (7 questions)
  {
    id: 'primary-goal',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What is their primary life goal?',
    options: [
      { value: 'success', label: 'Career Success/Achievement' },
      { value: 'love', label: 'Love and Family' },
      { value: 'freedom', label: 'Freedom and Independence' },
      { value: 'security', label: 'Security and Stability' },
      { value: 'justice', label: 'Justice/Making a Difference' },
      { value: 'knowledge', label: 'Knowledge and Understanding' },
      { value: 'survival', label: 'Survival/Basic Needs' },
      { value: 'other', label: 'Other', allowCustomInput: true },
    ],
  },
  {
    id: 'motivation-source',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What primarily motivates them?',
    options: [
      { value: 'ambition', label: 'Ambition/Achievement' },
      { value: 'fear', label: 'Fear/Avoidance of Loss' },
      { value: 'love', label: 'Love/Connection' },
      { value: 'duty', label: 'Duty/Responsibility' },
      { value: 'revenge', label: 'Revenge/Justice' },
      { value: 'curiosity', label: 'Curiosity/Discovery' },
      { value: 'survival', label: 'Survival Instinct' },
    ],
  },
  {
    id: 'greatest-desire',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What do they desire most?',
    options: [
      { value: 'acceptance', label: 'Acceptance and Belonging' },
      { value: 'power', label: 'Power and Control' },
      { value: 'peace', label: 'Peace and Contentment' },
      { value: 'recognition', label: 'Recognition and Fame' },
      { value: 'redemption', label: 'Redemption/Second Chance' },
      { value: 'truth', label: 'Truth and Understanding' },
      { value: 'change', label: 'Change/Transformation' },
    ],
  },
  {
    id: 'greatest-fear',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What is their greatest fear?',
    options: [
      { value: 'failure', label: 'Failure/Inadequacy' },
      { value: 'abandonment', label: 'Abandonment/Loneliness' },
      { value: 'loss-control', label: 'Loss of Control' },
      { value: 'death', label: 'Death/Mortality' },
      { value: 'rejection', label: 'Rejection/Judgment' },
      { value: 'vulnerability', label: 'Vulnerability/Weakness' },
      { value: 'change', label: 'Change/Unknown' },
    ],
  },
  {
    id: 'secret-dream',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What is their secret dream or aspiration?',
    options: [
      { value: 'creative', label: 'Creative Pursuit (art, music, writing)' },
      { value: 'adventure', label: 'Adventure/Travel' },
      { value: 'different-life', label: 'Completely Different Life' },
      { value: 'reconciliation', label: 'Reconciliation with Someone' },
      { value: 'recognition', label: 'Recognition for Hidden Talent' },
      { value: 'escape', label: 'Escape Current Situation' },
      { value: 'other', label: 'Other', allowCustomInput: true },
    ],
  },
  {
    id: 'values',
    section: 'Goals & Motivations',
    type: 'checkbox',
    question: 'What do they value most? (choose up to 3):',
    options: [
      { value: 'honesty', label: 'Honesty/Integrity' },
      { value: 'loyalty', label: 'Loyalty/Commitment' },
      { value: 'freedom', label: 'Freedom/Independence' },
      { value: 'family', label: 'Family/Relationships' },
      { value: 'success', label: 'Success/Achievement' },
      { value: 'justice', label: 'Justice/Fairness' },
      { value: 'compassion', label: 'Compassion/Kindness' },
      { value: 'knowledge', label: 'Knowledge/Truth' },
    ],
  },
  {
    id: 'life-philosophy',
    section: 'Goals & Motivations',
    type: 'radio',
    question: 'What is their life philosophy?',
    options: [
      { value: 'optimistic', label: 'Optimistic/Hopeful' },
      { value: 'pessimistic', label: 'Pessimistic/Cynical' },
      { value: 'realistic', label: 'Realistic/Pragmatic' },
      { value: 'idealistic', label: 'Idealistic/Dreamer' },
      { value: 'nihilistic', label: 'Nihilistic/Existential' },
      { value: 'spiritual', label: 'Spiritual/Faith-Based' },
    ],
  },

  // Conflicts & Challenges (7 questions)
  {
    id: 'main-flaw',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'What is their main character flaw?',
    options: [
      { value: 'pride', label: 'Pride/Arrogance' },
      { value: 'stubbornness', label: 'Stubbornness' },
      { value: 'impulsiveness', label: 'Impulsiveness/Recklessness' },
      { value: 'insecurity', label: 'Insecurity/Self-Doubt' },
      { value: 'selfishness', label: 'Selfishness' },
      { value: 'dishonesty', label: 'Dishonesty/Deception' },
      { value: 'cowardice', label: 'Cowardice/Avoidance' },
      { value: 'jealousy', label: 'Jealousy/Envy' },
    ],
  },
  {
    id: 'internal-conflict',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'What is their primary internal conflict?',
    options: [
      { value: 'identity', label: 'Identity Crisis/Self-Discovery' },
      { value: 'guilt', label: 'Guilt/Regret from Past' },
      { value: 'duty-vs-desire', label: 'Duty vs. Personal Desire' },
      { value: 'trust', label: 'Trust Issues' },
      { value: 'self-worth', label: 'Self-Worth/Confidence' },
      { value: 'moral-dilemma', label: 'Moral Dilemma' },
      { value: 'fear', label: 'Overcoming Fear' },
    ],
  },
  {
    id: 'external-obstacle',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'What is their main external obstacle?',
    options: [
      { value: 'antagonist', label: 'Antagonist/Enemy' },
      { value: 'society', label: 'Society/System' },
      { value: 'family', label: 'Family Expectations/Pressure' },
      { value: 'poverty', label: 'Poverty/Financial Struggle' },
      { value: 'illness', label: 'Illness/Disability' },
      { value: 'circumstances', label: 'Circumstances Beyond Control' },
      { value: 'competition', label: 'Competition/Rivalry' },
    ],
  },
  {
    id: 'past-trauma',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'Do they have significant past trauma?',
    options: [
      { value: 'none', label: 'No Significant Trauma' },
      { value: 'loss', label: 'Loss of Loved One' },
      { value: 'abuse', label: 'Abuse (physical, emotional, etc.)' },
      { value: 'betrayal', label: 'Betrayal by Someone Close' },
      { value: 'failure', label: 'Major Failure/Humiliation' },
      { value: 'accident', label: 'Accident/Near-Death Experience' },
      { value: 'abandonment', label: 'Abandonment' },
    ],
  },
  {
    id: 'coping-mechanism',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'What is their primary coping mechanism?',
    options: [
      { value: 'humor', label: 'Humor/Jokes' },
      { value: 'work', label: 'Work/Keeping Busy' },
      { value: 'isolation', label: 'Isolation/Withdrawal' },
      { value: 'substances', label: 'Substances (alcohol, drugs, etc.)' },
      { value: 'relationships', label: 'Seeking Relationships/Support' },
      { value: 'denial', label: 'Denial/Avoidance' },
      { value: 'aggression', label: 'Aggression/Acting Out' },
    ],
  },
  {
    id: 'weakness',
    section: 'Conflicts & Challenges',
    type: 'checkbox',
    question: 'Select their key weaknesses (choose up to 3):',
    options: [
      { value: 'impatient', label: 'Impatient' },
      { value: 'judgmental', label: 'Judgmental' },
      { value: 'naive', label: 'Naive/Gullible' },
      { value: 'controlling', label: 'Controlling' },
      { value: 'defensive', label: 'Defensive' },
      { value: 'pessimistic', label: 'Pessimistic' },
      { value: 'indecisive', label: 'Indecisive' },
      { value: 'secretive', label: 'Secretive/Closed-Off' },
    ],
  },
  {
    id: 'growth-area',
    section: 'Conflicts & Challenges',
    type: 'radio',
    question: 'What area do they need to grow in most?',
    options: [
      { value: 'self-acceptance', label: 'Self-Acceptance' },
      { value: 'forgiveness', label: 'Forgiveness (self or others)' },
      { value: 'courage', label: 'Courage/Bravery' },
      { value: 'empathy', label: 'Empathy/Understanding' },
      { value: 'responsibility', label: 'Responsibility/Maturity' },
      { value: 'trust', label: 'Trust/Openness' },
      { value: 'balance', label: 'Balance/Moderation' },
    ],
  },

  // Voice & Expression (5 questions)
  {
    id: 'speech-pattern',
    section: 'Voice & Expression',
    type: 'radio',
    question: 'How do they speak?',
    options: [
      { value: 'eloquent', label: 'Eloquent/Well-Spoken' },
      { value: 'casual', label: 'Casual/Informal' },
      { value: 'terse', label: 'Terse/Few Words' },
      { value: 'rambling', label: 'Rambling/Verbose' },
      { value: 'formal', label: 'Formal/Proper' },
      { value: 'slang', label: 'Slang/Street Talk' },
      { value: 'poetic', label: 'Poetic/Metaphorical' },
    ],
  },
  {
    id: 'vocabulary',
    section: 'Voice & Expression',
    type: 'radio',
    question: 'What is their vocabulary level?',
    options: [
      { value: 'simple', label: 'Simple/Basic' },
      { value: 'average', label: 'Average/Everyday' },
      { value: 'sophisticated', label: 'Sophisticated/Educated' },
      { value: 'technical', label: 'Technical/Specialized' },
      { value: 'colorful', label: 'Colorful/Expressive' },
      { value: 'limited', label: 'Limited/Struggles with Words' },
    ],
  },
  {
    id: 'emotional-expression',
    section: 'Voice & Expression',
    type: 'radio',
    question: 'How do they express emotions?',
    options: [
      { value: 'openly', label: 'Openly/Freely' },
      { value: 'reserved', label: 'Reserved/Controlled' },
      { value: 'dramatic', label: 'Dramatic/Intense' },
      { value: 'suppressed', label: 'Suppressed/Hidden' },
      { value: 'physical', label: 'Physical (gestures, actions)' },
      { value: 'indirect', label: 'Indirect/Subtle' },
    ],
  },
  {
    id: 'tone',
    section: 'Voice & Expression',
    type: 'radio',
    question: 'What is their typical tone?',
    options: [
      { value: 'warm', label: 'Warm/Friendly' },
      { value: 'cold', label: 'Cold/Distant' },
      { value: 'sarcastic', label: 'Sarcastic/Ironic' },
      { value: 'serious', label: 'Serious/Grave' },
      { value: 'playful', label: 'Playful/Light' },
      { value: 'aggressive', label: 'Aggressive/Harsh' },
      { value: 'gentle', label: 'Gentle/Soft' },
    ],
  },
  {
    id: 'distinctive-phrase',
    section: 'Voice & Expression',
    type: 'radio',
    question: 'Do they have a distinctive speech pattern or catchphrase?',
    options: [
      { value: 'catchphrase', label: 'Yes, a catchphrase or repeated saying' },
      { value: 'accent', label: 'Yes, a distinctive accent or dialect' },
      { value: 'verbal-tic', label: 'Yes, a verbal tic or filler word' },
      { value: 'unique-style', label: 'Yes, a unique speaking style' },
      { value: 'none', label: 'No distinctive pattern' },
    ],
  },

  // Story Role & Arc (6 questions)
  {
    id: 'narrative-role',
    section: 'Story Role & Arc',
    type: 'radio',
    question: 'What is their primary role in the story?',
    options: [
      { value: 'protagonist', label: 'Protagonist/Main Character' },
      { value: 'deuteragonist', label: 'Deuteragonist/Secondary Lead' },
      { value: 'love-interest', label: 'Love Interest' },
      { value: 'mentor', label: 'Mentor/Guide' },
      { value: 'antagonist', label: 'Antagonist/Villain' },
      { value: 'sidekick', label: 'Sidekick/Best Friend' },
      { value: 'foil', label: 'Foil/Contrast Character' },
      { value: 'supporting', label: 'Supporting Character' },
    ],
  },
  {
    id: 'character-arc',
    section: 'Story Role & Arc',
    type: 'radio',
    question: 'What type of character arc will they have?',
    options: [
      { value: 'positive-change', label: 'Positive Change/Growth' },
      { value: 'negative-change', label: 'Negative Change/Fall' },
      { value: 'flat-arc', label: 'Flat Arc (stays the same, changes world)' },
      { value: 'redemption', label: 'Redemption Arc' },
      { value: 'corruption', label: 'Corruption Arc' },
      { value: 'coming-of-age', label: 'Coming-of-Age/Maturation' },
      { value: 'disillusionment', label: 'Disillusionment Arc' },
    ],
  },
  {
    id: 'story-function',
    section: 'Story Role & Arc',
    type: 'checkbox',
    question: 'What functions do they serve in the plot? (choose all that apply):',
    options: [
      { value: 'drive-plot', label: 'Drive the Main Plot Forward' },
      { value: 'provide-conflict', label: 'Provide Conflict/Obstacles' },
      { value: 'comic-relief', label: 'Comic Relief' },
      { value: 'emotional-support', label: 'Emotional Support/Grounding' },
      { value: 'reveal-info', label: 'Reveal Information/Exposition' },
      { value: 'moral-compass', label: 'Moral Compass/Voice of Reason' },
      { value: 'catalyst', label: 'Catalyst for Change' },
      { value: 'mirror', label: 'Mirror/Reflection of Protagonist' },
    ],
  },
  {
    id: 'relationship-to-mc',
    section: 'Story Role & Arc',
    type: 'radio',
    question: 'What is their relationship to the main character?',
    options: [
      { value: 'is-mc', label: 'They ARE the main character' },
      { value: 'ally', label: 'Ally/Friend' },
      { value: 'family', label: 'Family Member' },
      { value: 'love-interest', label: 'Love Interest' },
      { value: 'rival', label: 'Rival/Competitor' },
      { value: 'enemy', label: 'Enemy/Antagonist' },
      { value: 'mentor', label: 'Mentor/Teacher' },
      { value: 'stranger', label: 'Stranger/Acquaintance' },
    ],
  },
  {
    id: 'story-impact',
    section: 'Story Role & Arc',
    type: 'radio',
    question: 'How much do they impact the story outcome?',
    options: [
      { value: 'critical', label: 'Critical/Story Cannot Happen Without Them' },
      { value: 'major', label: 'Major/Significantly Affects Outcome' },
      { value: 'moderate', label: 'Moderate/Important but Not Essential' },
      { value: 'minor', label: 'Minor/Small Impact' },
      { value: 'symbolic', label: 'Symbolic/Thematic Importance' },
    ],
  },
  {
    id: 'transformation',
    section: 'Story Role & Arc',
    type: 'radio',
    question: 'What will they learn or realize by the end?',
    options: [
      { value: 'self-worth', label: 'Their Own Worth/Value' },
      { value: 'truth', label: 'An Important Truth' },
      { value: 'forgiveness', label: 'How to Forgive' },
      { value: 'love', label: 'How to Love/Be Loved' },
      { value: 'strength', label: 'Their Own Strength' },
      { value: 'acceptance', label: 'Acceptance of Reality' },
      { value: 'responsibility', label: 'Responsibility/Consequences' },
      { value: 'other', label: 'Other', allowCustomInput: true },
    ],
  },
];
